_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.10
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.10
            "13": linux-x86_64
epochs:
    value: 2000
